version: "3.8"

networks:
  default:
    name: kdt

volumes:
  data:
    driver: local

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - data:/data
    platform: linux/x86_64
    restart: always

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
    platform: linux/x86_64
    restart: always